name: develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  x64-v4l2:
    runs-on: ubuntu-latest

    steps:
    - name: Install libv4l2
      run: sudo apt install libv4l-dev -y
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DBOARD=V4L2 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_WEBRTC_SAMPLES=ON -DBUILD_KVS_SAMPLES=ON -DBUILD_SAVE_FRAME_SAMPLES=ON

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel 4

    - name: Test
      run: ctest -C ${{ env.BUILD_TYPE }}

  x64-file:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DBOARD=FILE -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_WEBRTC_SAMPLES=ON -DBUILD_KVS_SAMPLES=ON -DBUILD_SAVE_FRAME_SAMPLES=ON

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel 4

    - name: Test
      run: ctest -C ${{ env.BUILD_TYPE }}
